@echo off
echo ^<?xml version="1.0" encoding="UTF-8"?^>> "%USERPROFILE%\.m2\settings.xml"
echo ^<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^<mirrors^>>> "%USERPROFILE%\.m2\settings.xml"
echo     ^<mirror^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<id^>aliyun^</id^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<mirrorOf^>central^</mirrorOf^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<name^>阿里云公共仓库^</name^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<url^>https://maven.aliyun.com/repository/public^</url^>>> "%USERPROFILE%\.m2\settings.xml"
echo     ^</mirror^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^</mirrors^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^<profiles^>>> "%USERPROFILE%\.m2\settings.xml"
echo     ^<profile^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<id^>aliyun^</id^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<repositories^>>> "%USERPROFILE%\.m2\settings.xml"
echo         ^<repository^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<id^>central^</id^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<url^>https://maven.aliyun.com/repository/public^</url^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<releases^>>> "%USERPROFILE%\.m2\settings.xml"
echo             ^<enabled^>true^</enabled^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^</releases^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<snapshots^>>> "%USERPROFILE%\.m2\settings.xml"
echo             ^<enabled^>true^</enabled^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^</snapshots^>>> "%USERPROFILE%\.m2\settings.xml"
echo         ^</repository^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^</repositories^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^<pluginRepositories^>>> "%USERPROFILE%\.m2\settings.xml"
echo         ^<pluginRepository^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<id^>central^</id^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<url^>https://maven.aliyun.com/repository/public^</url^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<releases^>>> "%USERPROFILE%\.m2\settings.xml"
echo             ^<enabled^>true^</enabled^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^</releases^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^<snapshots^>>> "%USERPROFILE%\.m2\settings.xml"
echo             ^<enabled^>true^</enabled^>>> "%USERPROFILE%\.m2\settings.xml"
echo           ^</snapshots^>>> "%USERPROFILE%\.m2\settings.xml"
echo         ^</pluginRepository^>>> "%USERPROFILE%\.m2\settings.xml"
echo       ^</pluginRepositories^>>> "%USERPROFILE%\.m2\settings.xml"
echo     ^</profile^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^</profiles^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^<activeProfiles^>>> "%USERPROFILE%\.m2\settings.xml"
echo     ^<activeProfile^>aliyun^</activeProfile^>>> "%USERPROFILE%\.m2\settings.xml"
echo   ^</activeProfiles^>>> "%USERPROFILE%\.m2\settings.xml"
echo ^</settings^>>> "%USERPROFILE%\.m2\settings.xml"
echo Maven settings.xml 文件已经创建在 %USERPROFILE%\.m2\settings.xml 